name: Deploy_videoplayer_to_GitHub_Pages
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install and Build
        run: npm install 

      - name: ls -la
        run: ls -la

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
#          dry-run: true

      - name: ls -la
        run: ls -la
